apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PrajwalBambulkar/two-tier-flask-app.git'
    targetRevision: main
    path: k8s/mysql   # only MySQL resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: mysql
      jsonPointers:
        - /spec/clusterIP

