apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-tier-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PrajwalBambulkar/two-tier-flask-app.git'
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

